### ISSUE TITLE
Use of ansible_ssh_user variable

### ISSUE THREAD

**Issue by gpfrancis** [genghisken/gkansible#2]
In gkservercollection/roles/severalnines_clustercontrol/tasks/secure-installation.yml we have several references to ansible_ssh_user that don't appear to be working for me - maybe something to do with the ansible version. However, this isn't very robust in any case, especially the way it is being used. Suggest replacing:
- /home/{{ ansible_ssh_user }} with {{ ansible_env.HOME }}
- ansible_ssh_user with ansible_user_id (when used for the user)
- ansible_ssh_user with ansible_effective_group_id (when used for the group).

**Comment by genghisken** [comment]
Good spot. Done and pushed. This will NOT be the only error you find here!
